services:
  univerdb:
    container_name: univerdb
    image: postgres:16.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: univer
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
