[tool.poetry]
name = "goit-web-hw-07"
version = "0.1.0"
package-mode = false
description = "homework 7"
authors = ["Y.Baranov"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
